### ISSUE TITLE
Trebor Scholz - interview for blog/book (until 15.7.)

### ISSUE THREAD

**Issue by ninabreznik** [RefugeesWork/organization#26]
On the soon to be remodeled site plaformcoop.net we are starting a blog.

Would you be willing to jot down a brief writeup/interview about refugeeswork?
If you could respond to the below questions, I could turn this into a blog post.  
But I would need to receive it by July 15th. It should not be longer than 1000 words, please.

TS: 
Nina, over the past few weeks he have spoken several times about your new project refugeeswork,  which  tries to connect refugees in Germany who are looking for work with people who  want to hire them on a freelance basis.
Please describe refugeeswork, who is involved, your motivation to build the site (don't forget to mention your friend Ali Ghali),  and its current status (number of registered accountants and number of active workers, etc).

NB:

TS: 
One is the things that where interesting in our conversation about the business structure of your site,  was that you decided to go for an LLC (Ltd,  in Germany, I believe) and that you registered that in the United Kingdom instead of Germany because it was administratively too difficult to do that there.  Refugeeswork  is not a platform cooperative as of now  and one of the reasons for that, you told me, is that you cannot see the advantage of a cooperative structure. Can you elaborate on that a little bit more?

NB:

TS:  
What are other comparable labor markets for refugees online?

NB:

TS:  
What are some of the challenges that you are currently facing and which opportunities do you see for the site?

NB:

[ We could include a video if you have for on any other material that further explains it.]

**Comment by serapath** [comment]
Hi Trebor, 
regarding the article, here we have it:
https://github.com/RefugeesWork/organization/blob/master/refugeeswork%20text%20latest%20version.pdf

Otherwise, regarding the preference for `Micro Holding Cooperativism` instead of a classic `Genossenschaft` is, that we want LITERALLY a bossless organization, which means we need to automate everything - so the rules inside the APP (platform) that allows people to do business with each other (partners & customers) determines everything - whether whats behind legally is a "genossenschaft" or a structure based on lots of individual "Ltd." that are bound together via CONTRACT LAW - doesnt matter, as long as everything that happens inside the APP is realiably legally binding :-)

So we want to brainstorm the rules under which we want to collaborate and built it into an APP (Platform) => The legal framework behind is an "implementation detail" which we will choose based on minimal bureauCrazy in order to make everything on the app a legally binding action.

We work together with people from Canada (Sensorica) and some folks from New Zealand (Enspiral) who rally around a concept they call "Value Flows" and "Network Resource Planning"
See: https://github.com/valueflows/valueflows/wiki

**Comment by ninabreznik** [comment]
Added:
TS: 
One is the things that where interesting in our conversation about the business structure of your site,  was that you decided to go for an LLC (Ltd,  in Germany, I believe) and that you registered that in the United Kingdom instead of Germany because it was administratively too difficult to do that there.  Refugeeswork  is not a platform cooperative as of now  and one of the reasons for that, you told me, is that you cannot see the advantage of a cooperative structure. Can you elaborate on that a little bit more?

NB:
Regarding the preference for Micro Holding Cooperativism instead of a classic Genossenschaft is, that we want LITERALLY a boss-less organisation, which means we need to automate everything. Therefore the rules inside the APP (platform) should allow people to do business with each other (partners & customers) and they should be automated and baked into the app in a form of contract law. 
It doesn't really matter if a legal structure behind is a "Genossenschaft" or a structure based on lots of individual "Ltd." that are connected together via contract law. What we saw with Ltd. is that there is an API so for example, if a new member joins with her/his Ltd. and gets the shares, this can be automatically changed in the constitution of the Ltd. that members co-own. And if people want to open a new co-owned Ltd., they can do that also online, without going to the notary, it can all be done simply online in couple of clicks (same if they want to terminate some of the co-owned structure). We believe that this helps people collaborate in a more flexible way.

Example: we would like to connect amount of shares in the co-owned structure with the work that is done. In order to do that efficiently, we need to develop a system that will enable us to co-decide which tasks are important for us and how much are they worth for each of the member. We are trying to implement a voting system that is based on voting with your own shares. So, when you think certain task is important, you promise your shares to the person who proposed the task. When task is done, shares are released. So, in order to get more shares, you need to do tasks that other support with their own shares and vice versa. 

We also explore the implementations of the system together with people from Canada (Sensorica) and some folks from New Zealand (Enspiral) who rally around a concept they call "Value Flows" and "Network Resource Planning"
See: https://github.com/valueflows/valueflows/wiki
